
<!ELEMENT vas-artikel (head, body) >


<!ELEMENT head (meta)+ >
<!ELEMENT meta (#PCDATA) >
<!ATTLIST meta
          type (class|name|type|prep|family|author|keyword) #REQUIRED >

<!-- 
    Überblicksartikel: section+
    Familien-/Musterartikel starten mit 'overview';
-->
<!ELEMENT body ((section)+ | (overview?, samples?, meaning?, section*, forms?, predicates?, references?)) >


<!--  =========================================================== -->
<!ENTITY % slots "rel | val | vrb | prp | effector | figure | ground" >
<!ELEMENT rel      (#PCDATA) >
<!ELEMENT val      (#PCDATA) >
<!ELEMENT vrb      (#PCDATA) >
<!ELEMENT prp      (#PCDATA) >
<!ELEMENT effector (#PCDATA) >
<!ELEMENT figure   (#PCDATA) >
<!ELEMENT ground   (#PCDATA) >


<!-- 
    Attribut nur in Ausnahmen verwenden; z.B. wenn Sample einer anderer Präposition im Artikel verwende. 
    
    Im Moment nur ein einziger Wert 'hi' (highlight) erlaubt. Hinweis ans Stylesheet, das Element in besonderer
    Weise hervorzuheben (z.B. analog zu den Artikel-Präpositionen)

    Änderung 22-03-18:
        nicht mehr notwendig, nachdem mehr SLOT-Elemente
        
<!ATTLIST rel       class (hi) #IMPLIED >
<!ATTLIST effector  class (hi) #IMPLIED >
<!ATTLIST figure    class (hi) #IMPLIED >
<!ATTLIST ground    class (hi) #IMPLIED >
-->

<!--  =========================================================== -->
<!ENTITY % references "link | xref | bibl-ref" >

<!-- 
    # LINKS

    ## externe Verweise

	starten mit 'http': 
	href="https://www.ids-mannheim.de/wichtigeSeite.html"
	
	<link href="https://www.spiegel.de">Spiegel<link>
     
	 
    ## WÖRTERBUCH interne Verweise 

	gehen über Dateinamen, relativ zum Textwurzelverzeichnis.
    Die Endung '.xml' entfällt; 
	Für MUSTER/FAMILIEN-Artikel OHNE führenden SLASH:
	
        href="von/von"            verweist auf den Überblicksartikel der Präposition 'von'
        href="vor/folge"          verweist auf den Familienartikel 'Folge' zu der Präposition 'vor'
        href="vor/verursachung"   verweist auf den Musterartikel 'Verursachung' zu der Präposition 'vor'
 
        (Soll später z.B. aus den Artikeln heraus auf Begleittexte verwiesen werden, dann MIT SLASH ausgehend von ROOT)
		href="/docs/hilfe-v1/was-Sie-immer-schon-über-verben-wissen-wollten.html"
	
    ## ARTIKEL interne Verweise

        Name des Elements des 'Groß-Blocks' + #: #overview, #meaning, #forms, #predicates
        ... siehe <link href="#meaning">Bedeutung</link>.
        
        soll auf eine 'section' (innerhalb eines 'Groß-Blocks') verwiesen werden, kommt der
        Wert des @label dazu, getrennt mit '/'
        ... siehe <link href="#meaning/Besonderheiten">Besonderheiten</link>.
    
	
    Es wird auch möglich sein, auf Textabschnitte anderer Musterartikel zu verweisen.
    <link href="vor/verursachung#meaning/Konzeptualisierung">Text zum Anklicken</link>
-->
<!ELEMENT link  (#PCDATA) >
<!ATTLIST link  href CDATA #REQUIRED >

<!-- 
-->
<!ELEMENT xref  EMPTY >
<!ATTLIST xref  href CDATA #REQUIRED >

<!-- 
    href entspricht ID der bibl-reference ...
    #PCDATA ist für die Stellenangabe.
        <bibl-ref href="Winkler 2019">S. 103</bibl-ref>
    Stylesheet nimmt sigle/href + Stellengabe, z.B. Winkler 2012 (S. 103)
    
-->
<!ELEMENT bibl-ref  (#PCDATA) >
<!ATTLIST bibl-ref  href CDATA #REQUIRED >

<!--  =========================================================== -->
<!ENTITY % rich-text	"b | i | obj-spr | sup | sub | sc | hi" >
<!ELEMENT obj-spr  (#PCDATA | sub | sup)* >
<!ELEMENT i        (#PCDATA | sub | sup)* >
<!ELEMENT b        (#PCDATA | sub | sup)* >
<!ELEMENT sup      (#PCDATA) >
<!ELEMENT sub      (#PCDATA) >
<!ELEMENT sc       (#PCDATA) >

<!-- 
    XSLT erstellt SPAN mit class="hi {@class}
    Die eigentliche Formatierung kann dann unabhängig von Transformation
    im CSS festgelegt werden. Dort z.Z. definiert classen:
    rel, figure, ground, effector
-->
<!ELEMENT hi      (#PCDATA) >
<!ATTLIST hi  class CDATA #REQUIRED >

<!--  =========================================================== -->
<!ELEMENT overview  (prototype) >
<!ELEMENT meaning   (p | examples | section)+ >

<!-- 
    TODO: Werte für Label absprechen
    
    #IMPLIED: label darf fehlen ... dann wird keine Überschrift generiert
-->
<!ELEMENT section ((p | examples | ul | illustration)+ | (predicate-list)+) >
<!ATTLIST section label  CDATA #IMPLIED 
                  class  CDATA #IMPLIED >

<!ELEMENT p (#PCDATA | %rich-text; | %references; | %slots; )* >
<!ELEMENT ul (li)+ >
<!ATTLIST ul class CDATA #IMPLIED >

<!ELEMENT li (#PCDATA | %rich-text; | %references; | %slots; )* >

<!ELEMENT illustration (img, caption?) >
<!ELEMENT caption (#PCDATA) >
<!ELEMENT img EMPTY >
<!ATTLIST img src CDATA #REQUIRED >


<!--  =========================================================== -->
<!ELEMENT prototype (pattern | examples | p)* >
<!ELEMENT pattern   (pitem)+ >
<!ATTLIST pattern
            id NMTOKEN #REQUIRED
            mtype NMTOKEN #IMPLIED >
<!-- 
    TODO Attributdefinitionen
-->
<!ELEMENT pitem EMPTY>
<!ATTLIST pitem
            sem  CDATA   #IMPLIED
            slot NMTOKEN #REQUIRED
            syn  CDATA   #REQUIRED >

<!ELEMENT  examples (xref)+ >


<!--  =========================================================== -->
<!ELEMENT samples (sample)+ >
<!ELEMENT sample (#PCDATA | %slots;)* >
<!ATTLIST sample id      NMTOKEN #REQUIRED 
                 cosmas  CDATA   #IMPLIED 
                 etc     CDATA   #IMPLIED>


<!--  =========================================================== --> 
<!-- 
    form-grp@label ist optional. Fehlt es, werden die Gruppen nur von
    einander abgesetzt
-->
<!ELEMENT forms (form-grp*, section?) >
<!ELEMENT form-grp (akt | kon | pass | ambig)* >
<!ATTLIST form-grp label  CDATA   #IMPLIED >

<!ELEMENT akt  (prototype)+ >
<!ELEMENT kon  (prototype)+ >
<!ELEMENT pass (prototype)+ >
<!ELEMENT ambig  (prototype)+ >


<!--  =========================================================== 
    Element 'section' kann predicate-list enthalten
-->
<!ELEMENT predicates (section)+ >
<!ELEMENT predicate-list (predicate)+>
<!ATTLIST predicate-list label CDATA #REQUIRED>
  
<!ELEMENT predicate (examples)+ >
<!ATTLIST predicate 
              value        CDATA #REQUIRED
              alt          CDATA #IMPLIED
              evalbu-ref   CDATA #IMPLIED >

<!--  =========================================================== 
    bibl-ref werden vom Stylesheet aufgelöst anhand zentraler Quellen-Datei
-->
<!ELEMENT references (bibl-ref | reference)+ >
<!ELEMENT reference (#PCDATA | %rich-text;)* >
<!ATTLIST reference id CDATA #REQUIRED >

