//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDS.VAS.Excel2Xml.XRefValidator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDS.VAS.Excel2Xml.XRefValidator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @tailwind base;
        ///@tailwind components;
        ///@tailwind utilities;
        ///
        ////* Libertinus - fetten Fonts von der ÖA ...arrgh */
        ///@font-face {
        ///  font-family: &apos;Libertinus&apos;;
        ///  font-style: normal;
        ///  font-weight: 400;
        ///  src: local(&quot;&quot;), url(&quot;/fonts/libertinus/LibertinusSerifRegular.woff2&quot;) format(&quot;woff2&quot;);
        ///}
        ///
        ///@font-face {
        ///  font-family: &apos;Libertinus&apos;;
        ///  font-style: italic;
        ///  font-weight: 400;
        ///  src: local(&quot;&quot;), url(&quot;/fonts/libertinus/LibertinusSerifItalic.woff2&quot;) format(&quot;woff2&quot;);
        ///}
        ///
        ///@font-face {
        ///  font-family: &apos; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Template_CSS {
            get {
                return ResourceManager.GetString("Template_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;html&gt;
        ///&lt;head&gt;&lt;style&gt;
        ///{{CSS}}
        ///&lt;/style&gt;&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div class=&quot;vas-doc&quot;&gt;
        ///&lt;div class=&quot;examples&quot;&gt;
        ///&lt;div class=&quot;head-lzga&quot;&gt;Belege&lt;/div&gt;
        ///{{SAMPLES}}
        ///&lt;/div&gt;
        ///&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt; ähnelt.
        /// </summary>
        internal static string Template_HTML {
            get {
                return ResourceManager.GetString("Template_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;div class=&quot;sample&quot;&gt;
        ///&lt;div class=&quot;sample-nr&quot;&gt;{{ID}}&lt;/div&gt;&lt;br/&gt;
        ///&lt;div class=&quot;sample-txt&quot;&gt;{{CONTENT}}&lt;/div&gt;
        ///&lt;/div&gt; ähnelt.
        /// </summary>
        internal static string Template_SAMPLE {
            get {
                return ResourceManager.GetString("Template_SAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;span class=&quot;{{CLASS}}&quot;&gt;{{TXT}}&lt;/span&gt; ähnelt.
        /// </summary>
        internal static string Template_SPAN {
            get {
                return ResourceManager.GetString("Template_SPAN", resourceCulture);
            }
        }
    }
}
